version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: getmein1234/get-me-in
      
    working_directory: /go/src/github.com/ProjectReferral/Get-me-in
    steps:
      - checkout
#       - run:
#           name: post checkout check
#           command: |
#             echo $PWD
#             ls -aslh .
#             ls -aslh ~
#             ls -aslh ~/tmp

      # specify any bash command here prefixed with `run: `

        - run: go version

      # - run: go get -v -t -d ./account-service/...
      # - run: go build -v ./account-service/cmd

      # - run: go get -v -t -d ./login-msvc/...
      # - run: go build -v ./login-msvc/cmd

      # - run: go get -v -t -d ./marketing-service/...
      # - run: go build -v ./marketing-service/cmd