version: 2.1
jobs:
  build:
    docker:
      - image: getmein1234/get-me-in
    steps:
      - checkout
      
      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          TAG=dev
          docker build -t getmein1234/get-me-in:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push CircleCI-Public/circleci-demo-docker:$TAG