version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      
      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build -t getmein1234/get-me-in:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push getmein1234/get-me-in:$TAG